<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Recipedia') ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/library/booklet/jquery.booklet.latest.css') 
                        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')  
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=EB+Garamond')
                        ?> 
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
         <div id="wrapper">
      		<!-- Sidebar -->
      		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     		   <!-- Brand and toggle get grouped for better mobile display -->
        		<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            		<span class="sr-only">Toggle navigation</span>
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
          		</button>
            	<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/steaming.bowl.png') ?>" alt="Recipedia" width="31px" height="20px"/>&nbsp;<?php echo $this->translate('RECIPEDIA') ?></a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav navbar-right navbar-user">	
            		<li class="dropdown alerts-dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alerts <span class="badge">3</span> <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><a href="#">Default <span class="label label-default">Default</span></a></li>
										<li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
										<li><a href="#">Success <span class="label label-success">Success</span></a></li>
										<li class="divider"></li>
										<li><a href="#">View All</a></li>
									</ul>
								</li>
								<li class="dropdown user-dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										<?php 
											if($this->zfcUserIdentity()) {
												echo $this->gravatar($this->zfcUserIdentity()->getEmail());
												echo $this->zfcUserIdentity()->getDisplayName(); 
												}
											else echo 'guest';
										?><b class="caret"></b>
									</a>
									<ul class="dropdown-menu">
										<li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
										<li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
										<li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
										<li class="divider"></li>
										<li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="fa fa-power-off"></i>Log Out</a></li>
									</ul>
								</li>
							</ul>
						</div><!-- /.navbar-collapse -->
					</nav>
        </div>
        <div class="container">
        	 <div class="row">
        		<div class="col-lg-9">
            		<?php echo $this->content; ?>
           			<hr>
            	</div>
        	    <div class="col-lg-3">
          			<div class="well">
        			 <h4>Side Widget Well</h4>
            		 <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
          			</div><!-- /well -->
        		</div>
      		</div>
            <hr>
            <footer>
      	 		<div class="row">
        	  		<div class="col-lg-12">
               			<p>&copy; 2013 - <?php echo date('Y') ?> by Shreeprabha Aggarwal. <?php echo $this->translate('All rights reserved.') ?></p>
              		</div>
           		</div>
      		</footer>
	    </div><!-- /.container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>