<?php

$title = 'Add new post';
$this->headTitle($title);
?>
<h1><?php 

echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', '/blog/post/add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('body'));

echo $this->formHidden($form->get('id'));

echo $this->formHidden($form->get('date')->setValue(date('Y-m-d')));

echo $this->formHidden($form->get('author')->setValue($this->zfcUserIdentity()->getEmail()));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

