<?php

$title = 'Add new Recipe';
$this->headTitle($title);
?>
<h1><?php 

echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', '/add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('preptime'));
echo $this->formRow($form->get('cooktime'));
echo $this->formRow($form->get('servings'));
echo $this->formRow($form->get('method'));
echo $this->formRow($form->get('visibility'));
echo $this->formRow($form->get('ingredients'));
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('author')->setValue($this->zfcUserIdentity()->getEmail()));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

