<?php

$title = 'Add new Recipe';
$this->headTitle($title);
?>
<h1><?php 

echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', '/application/index/add');
$form->prepare();

echo $this->form()->openTag($form);
?>
<p><?php echo $this->formRow($form->get('title'));?></p>
<p><?php echo $this->formRow($form->get('preptime'));?></p>
<p><?php echo $this->formRow($form->get('cooktime'));?></p>
<p><?php echo $this->formRow($form->get('servings'));?></p>
<p><?php echo $this->formRow($form->get('method'));?></p>
<p><?php echo $this->formRow($form->get('visibility'));?></p>
<p><?php echo $this->formRow($form->get('ingredients'));?></p>
<p><?php echo $this->formHidden($form->get('id'));?></p>
<p><?php echo $this->formHidden($form->get('author')->setValue($this->zfcUserIdentity()->getEmail()));?></p>

<p><?php echo $this->formSubmit($form->get('submit'));?></p>
<?php echo $this->form()->closeTag();
?>

