<h1><?php echo $this->escapeHtml("The latest Recipe Book"); ?></h1>
<?php echo $this->inlineScript() 
	->prependFile($this->basePath() . '/library/booklet/jquery-ui-1.10.1.custom.min.js')
            ->prependFile($this->basePath() . '/library/booklet/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/library/booklet/jquery.booklet.latest.min.js')
     ?>
	<script type="text/javascript">
	    $(function () {		
	        $("#mybook").booklet({ closed:true, pageNumbers: false });
	    });
    </script>
    <div id="mybook">
	        <div class="b-page-cover b-wrap" title="first page">
	            <h3><?php echo $this->zfcUserIdentity()->getDisplayname();?>&rsquo;s Recipe Book</h3>
	        </div>
	        <?php foreach($recipes as $recipe) : ?>
	        <div title="page">
	            <p><?php echo $this->escapeHtml($recipe->title);?></p>
	            <p><?php echo $this->escapeHtml($recipe->ingredients);?></p>
	            <p><?php echo $this->escapeHtml($recipe->preptime);?></p>
	            <p><?php echo $this->escapeHtml($recipe->cooktime);?></p>
	            <p><?php echo $this->escapeHtml($recipe->servings);?></p>
	            <p><?php echo $this->escapeHtml($recipe->method);?></p>     
	        </div>
	        <?php endforeach;?>
	        <div class=" b-page-cover b-wrap" title="page">
	            <h3>Back Cover</h3>
	        </div>
	        
	 </div>


