	<?php echo $this->inlineScript() 
	->prependFile($this->basePath() . '/library/booklet/jquery-ui-1.10.1.custom.min.js')
            ->prependFile($this->basePath() . '/library/booklet/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/library/booklet/jquery.booklet.latest.min.js')
     ?>
	<script type="text/javascript">
	    $(function () {		
	        $("#mybook").booklet({ closed:true, pageNumbers: false });
	    });
    </script>
    <div id="mybook">
	        <div class="b-page-cover b-wrap" title="first page">
	            <h3>Page 1</h3>
	        </div>
	        <div title="second page">
	            <h3>Page 2</h3>
	        </div>
	        <div title="third page">
	            <h3>Page 3</h3>
	        </div>
	        <div title="fourth page">
	            <h3>Page 4</h3>
	        </div>
	        <div title="fifth page">
	            <h3>Page 5</h3>
	        </div>
	        <div class=" b-page-cover b-wrap" title="sixth page">
	            <h3>Page 6</h3>
	        </div>
	        
	 </div>