<h1><?php echo $this->escapeHtml("The Food Blog"); ?></h1>
<?php if($this->zfcUserIdentity()) : ?>
<p><a class="btn btn-primary" href="/blog/post/add">Add a new Post! <span class="glyphicon glyphicon-chevron-right"></span></a><p>
	<?php foreach($posts as $post) : ?>
		<h2><a href="#"><?php echo $this->escapeHtml($post->title);?></a></h2>
		<p class="lead">by <?php echo $this->gravatar($this->escapeHtml($post->author));?>
			<?php if($this->zfcUserIdentity()->getEmail() == $this->escapeHtml($post->author)) : ?>
				<a href="/blog/post/edit/<?php echo $post->id; ?>">Edit</a>
        		<a href="/blog/post/delete/<?php echo $post->id; ?>">Delete</a>
        	<?php endif;?>
		</p>
		<hr>
		<p><i class="fa fa-calendar"></i><?php echo $this->escapeHtml($post->date);?></p>
		<hr>
		<p><?php if (strlen($this->escapeHtml($post->body)) > 250) : ?>
				<?php echo substr($this->escapeHtml($post->body), 0, 250); ?>
				<a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
			<?php else : ?>
				<?php echo $this->escapeHtml($post->body); ?>
			<?php endif;?>
		</p>
		<hr>
	<?php endforeach; ?>		
<?php endif;?>


